479 feat add notes to queued cocktail
jo-gross/Cocktail-Manager pull request #480
Opened 2024-12-13 17:55 UTC by jo-gross

## Closing issues:

- Closes: #479 

## Before you mark this PR as ready, please check the following points

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I´e created all necessary migrations?
- [x] The format is correct (`pnpm format:check`, if invalid `pnpm format:fix`)
- [x] No build errors (`pnpm build`)
- [x] I´ve tested the implemented function by my own
- [x] Ensure the pr title fits the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) standard

## Describe your work, what changed

1. Adding Cocktails with Notes to the Queue:

    - It is now possible to queue (multiple) cocktails with individual notes.
    - Cocktails with the same name but different notes are grouped separately, with identical names and notes are still grouped together.

2. Queue Behavior:

    - Cocktails in the queue are grouped by name and notes, with the option to mark them as "made" or "canceled."
    - Detail View (opened from the queue): any attached notes are displayed at the top. Clicking the "made" button removes the item with the displayed note from the queue, if no items remain, the view automatically closes.

3. Behavior of the "Made" Button (e.g., Search, Cocktail Card, or Detail View):
    - If there are queue items without notes, they are removed when the "made" button is pressed.
    - If it's unclear which specific cocktail is meant, a clarification prompt appears.
    - If only items with notes exist, you are prompted to either remove one of them or track the action without removing any.

## Affected sites (please check during review):

- [ ] [workspaceId]/index - anything with the queue/statistic components

2024-12-16 23:00 UTC, fypsilonnn requested changes
as personally discussed

2024-12-17 08:26 UTC, jhns-de approved these changes

2024-12-21 18:12 UTC, fypsilonnn requested changes
sometimes the wrong iteration of a cocktail gets deleted out of the queue when using the "x"
First you put in queue some number of e.g. margaritas and give them a note, then you add a few without any notes using the "Liste" or the "mit Notiz" button. Then when trying to delete a drink without a note using the red x in the queue it will delete a drink with a note instead of the one without any notes. This makes it impossible to delete any non-note drinks without clearing any previously added drinks with notes.
The same happens when having two iterations of a drink with notes and then adding a third one without notes
Any noted-drinks you add afterwards however will work fine. Adding noted drinks and trying to delete them will also work

2024-12-27 18:44 UTC, jo-gross commented
> sometimes the wrong iteration of a cocktail gets deleted out of the queue when using the "x" First you put in queue some number of e.g. margaritas and give them a note, then you add a few without any notes using the "Liste" or the "mit Notiz" button. Then when trying to delete a drink without a note using the red x in the queue it will delete a drink with a note instead of the one without any notes. This makes it impossible to delete any non-note drinks without clearing any previously added drinks with notes. The same happens when having two iterations of a drink with notes and then adding a third one without notes Any noted-drinks you add afterwards however will work fine. Adding noted drinks and trying to delete them will also work

Well spotted, thank you very much – it should now be fixed. :)

2025-01-07 17:59 UTC, fypsilonnn approved these changes

2025-01-07 18:42 UTC, merged